#
# extra_scripts/build_info.py
#
import os
from datetime import datetime

# from SCons.Script import Import
Import("env")

fw_version = env.GetProjectOption("custom_firmware_version") or "0.0.0"
build_ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

proj_dir = env.subst("$PROJECT_DIR")
inc_dir = os.path.join(proj_dir, "include")
os.makedirs(inc_dir, exist_ok=True)

hdr = os.path.join(inc_dir, "build_info.h")
with open(hdr, "w") as f:
    f.write("// AUTO-GENERATED by build_info.py\n")
    f.write("#pragma once\n\n")
    f.write(f'#define BUILD_VERSION   "{fw_version}"\n')
    f.write(f'#define BUILD_TIMESTAMP "{build_ts}"\n')
